### ISSUE TITLE
Multi-ad on one location : Its confusing people

### ISSUE THREAD

**Issue by vinvin27** [Ydalb/mapicoin#32]
I think when we got multiples ads on one location its confusing people.

For example : 

https://mapicoin.fr/?u=https://www.leboncoin.fr/locations/offres/rhone_alpes/rhone/%3Fth=1%26f=p%26location=Tassin-la-Demi-Lune%2069160%26mrs=300%26mre=950

38 ads, one pin (maybe add + or different color) 

And, when we got only 1 pin it zoom too much. On this example, we can believe map is not load but no just too much zoom (grey background) :)

**Comment by Ydalb** [comment]
Zoom fixed 🐙
